###

### Api get all tasks
GET http://localhost:8080/api/v1/tasks
Content-Type: application/json

###

### Api get task by id
GET http://localhost:8080/api/v1/tasks/1
Content-Type: application/json

###

### Api create task
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "title": "Complete project documentation",
  "description": "Write and finalize the project documentation.",
  "priority": "HIGH",
  "dueDate": "2025-04-10 15:00:00"
}

###

### Api update task with id 1

PUT http://localhost:8080/api/v1/tasks/1
Content-Type: application/json

{
  "title": "Updated Task Title",
  "description": "Updated description of the task.",
  "status": "IN_PROGRESS",
  "priority": "MEDIUM",
  "dueDate": "2025-04-15 10:00:00"
}

###

### Api delete task with id 1

DELETE http://localhost:8080/api/v1/tasks/1
Content-Type: application/json

###